In [1]:
#load libraries w/ iris datset
from sklearn.datasets import load_iris
#load scikit's learn random forest classifier library
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
np.random.seed(0)


In [2]:
#loading data from the iris_dataet
iris=load_iris()
#create an obj called iris w/ the feature variable
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()#printing first 5 row

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
#printing iris_datset's data contents
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
#printing feature attributes of the iris datasets
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
#number of records in the iris dataset
len(iris.data)

150

In [6]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9     

In [7]:
#add a new column w/ the species names, this is what we are going to try to predict
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
#view the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [8]:
iris.target #factorization depending upon targrt_name we are dividing into 0,1,2 index

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica

In [11]:
#divide all rows in the dataset into training set and test set
#we shall generate random numbers w/ in the range of 0 to 1 & those values less than or equal to .75 against them
#we shall put true in a new attribute is_training or false otherwise
df['is_train']=np.random.uniform(0,1,len(df))<=.75
#view the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [12]:
#segregation of training & test datasets
#creating two new datframes, one w/ the traing rows and anther one w/ test rows
train, test = df[df["is_train"]==True],df[df["is_train"]==False]

In [13]:
print("Number of row in training & test DataFrames are {} and {}"\
      .format(len(train),len(test)))

Number of row in training & test DataFrames are 118 and 32


In [14]:
#now preprocessing the data
#create a list of the feature column's names
features=df.columns[:4]
#view features
(features)


Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [15]:
train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
9                  4.9               3.1                1.5               0.1   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
22                 4.6               3.6                1.0               0.2   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
30                 4.8               3.1                1.6               0.2   
32                 5.2               4.1                1.5               0.1   
33                 5.5               4.2                1.4               0.2   
34                 4.9               3.1                1.5               0.1   
35                 5.0               3.2                1.2               0.2   
36                 5.5               3.5                1.3               0.2   
37                 4.9               3.1                1.5               0.1   
39                 5.1               3.4                1.5               0.2   
40                 5.0               3.5                1.3               0.3   
41                 4.5               2.3                1.3               0.3   
42                 4.4               3.2                1.3               0.2   
..                 ...               ...                ...               ...   
110                6.5               3.2                5.1               2.0   
112                6.8               3.0                5.5               2.1   
113                5.7               2.5                5.0               2.0   
115                6.4               3.2                5.3               2.3   
117                7.7               3.8                6.7               2.2   
119                6.0               2.2                5.0               1.5   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4              

In [16]:
#now convert three species category into number of 0,1,2
y=pd.factorize(train['species'])[0]

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [18]:
#now the very importent step. here we shall train the model.
#create a random forest classifier, by convention clf means means a classifier
clf=RandomForestClassifier(n_jobs=2,random_state=0)
#train the classifier to take the training and learn how they relate to the tring y(the species)\
clf.fit(train[features],y)#train[features]-> train attributes and y-> target value
train[features]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
9                  4.9               3.1                1.5               0.1
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
22                 4.6               3.6                1.0               0.2
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
30                 4.8               3.1                1.6               0.2
32                 5.2               4.1                1.5               0.1
33                 5.5               4.2                1.4               0.2
34                 4.9               3.1                1.5               0.1
35                 5.0               3.2                1.2               0.2
36                 5.5               3.5                1.3               0.2
37                 4.9               3.1                1.5               0.1
39                 5.1               3.4                1.5               0.2
40                 5.0               3.5                1.3               0.3
41                 4.5               2.3                1.3               0.3
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
110                6.5               3.2                5.1               2.0
112                6.8               3.0                5.5               2.1
113                5.7               2.5                5.0               2.0
115                6.4               3.2                5.3               2.3
117                7.7               3.8                6.7               2.2
119                6.0               2.2                5.0               1.5
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1     

In [19]:
#thus I have completed the trainig of my learning odel. Now we shall test the performance of our odel testig w/ our test dataset
#apply the classifier we test dataset (which , we never used before)
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [20]:
#as we are having three ctegories, so the distinct values are 0,1 and 2
#now we shall view probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0.9, 0.1, 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ]])

In [21]:
#consider any row have values e.g: 0.8, 0.1 and 0.1.then it means probability is 80% for category-1 and 10% each for category-3.

In [22]:
#evalution of the classifier
#create actual english names for the plants for each predicted plant class
preds=iris.target_names[clf.predict(test[features])]
#view the PREDICTED species for the first five observstions
preds[0:5]
#type(iris.target_names)

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [23]:
#view the actual species names for the first five observations
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [24]:
#creating a confusion matrix
#this confusion matrix will tell us that for how many species were having same predicted species name and number of species where
# they got wrongly predicted
pd.crosstab(test['species'],preds,rownames=['actual species'],\
           colnames=['predicted species'])

predicted species  setosa  versicolor  virginica
actual species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [25]:
#view feature importance
#view a list of the features and their importance scores
list(zip(train[features],clf.feature_importances_))

[('sepal length (cm)', 0.11185992930506346),
 ('sepal width (cm)', 0.016341813006098178),
 ('petal length (cm)', 0.36439533040889194),
 ('petal width (cm)', 0.5074029272799464)]